# Threshold distance - how much each joint can be away from predefined position
max_distance_rad: 0.35 # about 20 degrees

# Time [in seconds] after which goal is aborted if no keep_alive message is received
stop_trajectory_timeout: 1.5

# Predefined poses. Path has to be relative to kalman_arm_config package
# ID must correspond to value in ArmPoseSelect message
poses:
    - id: 0
      name: "Compact Herman"
      path: "predefined_poses/compact_herman.yaml"
      joints_set:
          ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
      joints_checked: ["joint_1", "joint_2", "joint_3"]
      joints_reversed: []
      safe_previous_poses: [2, 3, 4, 5, 6]
    - id: 1
      name: "Reset 4 and 6"
      path: "predefined_poses/reset.yaml"
      joints_set: ["joint_4", "joint_6"]
      joints_checked: []
      joints_reversed: ["joint_5"]
      safe_previous_poses: []
    - id: 2
      name: "Base Front"
      path: "predefined_poses/base_front.yaml"
      joints_set:
          ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
      joints_checked: ["joint_2", "joint_3"]
      joints_reversed: []
      safe_previous_poses: [0, 3, 4, 5, 6]
    - id: 3
      name: "Base Left"
      path: "predefined_poses/base_left.yaml"
      joints_set:
          ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
      joints_checked: ["joint_2", "joint_3"]
      joints_reversed: []
      safe_previous_poses: [0, 2, 4, 5]
    - id: 4
      name: "Base Right"
      path: "predefined_poses/base_right.yaml"
      joints_set:
          ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
      joints_checked: ["joint_2", "joint_3"]
      joints_reversed: []
      safe_previous_poses: [0, 2, 3, 5]
    - id: 5
      name: "Based"
      path: "predefined_poses/reset.yaml"
      joints_set:
          ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
      joints_checked: []
      joints_reversed: []
      safe_previous_poses: [0, 2, 3, 4, 5, 6]
    - id: 6
      name: "Spectro approach"
      path: "predefined_poses/spectro_approach.yaml"
      joints_set:
          ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
      joints_checked: ["joint_2", "joint_3"]
      joints_reversed: []
      safe_previous_poses: [0, 2, 5]
