kalman_arm:
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_search_resolution: 0.0050000000000000001
  # kinematics_solver_timeout: 0.0050000000000000001
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 0.05 # this timeout parameter is actually ignored by servo
  kinematics_solver_attempts: 1.0
  mode: local 