# Common configuration of realsense2_camera nodes.
# This is NOT a well-formed ROS param file.

align_depth:
  enable: true
rgb_camera:
  color_profile: 1280x720x15
depth_module:
  depth_profile: 640x360x15
